junis3/cstodo

src/index.ts

이것만 PR로 날리고 새로 clone해서 거기서작업할게요

Formatting TODOs

---

src/index.ts

* cstodo format 명령어 응답 결과에 :keycap_star: 이모지 추가
* cstodo add 명령어의 인자가 없을 때 알림 메시지 수정
* 106라인 `remainingTodos` const로 변경
* None

add keycap_star emoji / fix empty add query alert

---

src/module/todo/onTodoAdd.ts
src/module/todo/onTodoRemove.ts

remove does nothing when it is faulty

Made cstodoRemove transactional

---

src/module/todo/onTodoAdd.ts
src/module/todo/onTodoEdit.ts
src/module/todo/onTodoRemove.ts
src/module/todo/onTodoSearch.ts

Cleared merge issues fragments

---

src/etc/postMessage.ts
src/etc/theme.ts
src/module/todo/onTodoAdd.ts
src/module/todo/onTodoAll.ts
src/module/todo/onTodoDefault.ts
src/module/todo/onTodoEdit.ts
src/module/todo/onTodoLength.ts
src/module/todo/onTodoRemove.ts
src/module/todo/onTodoSearch.ts
src/module/todo/onTodoTheme.ts

replyMessage가 복잡하고 erroneous해서
replySuccess | replyDdokddul (expected exceptional cases) | replyFail 로 분리.
replyMessage를 unexport하고 싶었지만 랜덤 blobaww때문에 못함

refactor replies for cstodo CRUD

---

src/config.ts
src/database/bar.ts
src/database/user.ts
src/etc/isInteger.ts
src/etc/postMessage.ts
src/etc/theme.ts
src/etc/validateBar.ts
src/module/bar/barFormatter.ts
src/module/bar/index.ts
src/module/bar/onBarAdd.ts
src/module/bar/onBarDefault.ts
src/module/bar/onBarEdit.ts
src/module/bar/onBarRemove.ts
src/module/onMessage.ts
src/module/todo/onTodoRemove.ts

progress bar 추가: CRUD

---

src/database/greengold.ts
src/database/history.ts
src/etc/postMessage.ts
src/etc/theme.ts
src/module/bar/onBarDefault.ts
src/module/onDailyGreenGold.ts
src/module/todo/index.ts
src/module/todo/onTodoHW.ts

haha
i did no test run for this pr

added hw command

---

src/config.ts
src/database/user.ts
src/etc/functionNameMap.ts
src/etc/recommendProblem.ts
src/module/onDailyGreenGold.ts
src/module/todo/onTodoHW.ts
src/module/todo/onTodoSet.ts

- `mytodo set --boj <BOJHandle>` 을 이용해 boj 핸들을 설정할 수 있음.
- 관리자에게 쿼리, 숙제 검사 간격을 설정하여 요청하면 DB에 관련 값을 추가.

enabled greengold 4 everyone

---

src/database/alarm.ts
src/database/greengold.ts
src/database/user.ts
src/etc/functionNameMap.ts
src/etc/recommendProblem.ts
src/module/bar/index.ts
src/module/bar/onBarHW.ts
src/module/onDailyGreenGold.ts

- 한 사람이 숙제를 여러 문제씩 받을 수 있음.
- 이제 새 유저 추가할 때 코드 수정 안해도 됨. alarm DB에 param만 잘 줘서 넣으면 된다
- 한 사람이 여러 쿼리로(!) 여러 숙제를 가져오는 건 안됨.
- TODO: 숙제를 풀었을 때 다음 숙제로 강제 갱신하는 기능

enabled multi-problem hw

---

src/config.ts

해당 값을 변경할 수 있어야 다른 슬랙에서 이용이 가능해서 환경 변수에서 이 값들도 설정할 수 있게 했습니다

env에 CSTODO_TEST_CHANNEL, CSTODO_CHANNEL 값 추가

---

src/etc/isInteger.ts

똑같은 동작 regex 쓰는 걸로 바꿨어요(유닛 테스트 전부 통과)

refactor isInteger function

---

src/module/bar/index.ts
src/module/code/index.ts
src/module/todo/index.ts
src/module/yourMark/index.ts

isAttack 함수 리팩토링 과정에서 해당 함수 사용하는 부분을 안 고친 곳이 있어 정상 동작하게 수정했습니다

isAttack await 수정

---

src/etc/getCurrentHistory.ts
src/etc/getProblemInfo.ts
src/module/todo/onTodoSet.ts

User-Agent 수정

---

src/command/AddReactionCommand.ts

xtreme hotfix

---

src/database/cstodo.ts
src/module/todo/onTodoEdit.ts

change PK to (content, owner, due) from the content

Correct bugs in todoEdit

---

src/database/cstodo.ts
src/etc/checkAllTodoAlarms.ts

기일이 지났거나 최대 하루 남은 일들에 대해 리마인더를 발송함.

Feat: support daily reminder

---

src/database/user.ts
src/etc/checkAllTodoAlarms.ts
src/module/todo/onTodoSet.ts

`cstodo set --use-alarm mention` 커맨드로 마감 시간에 멘션을 받을 수 있음.
muted인 경우 DM으로, 그렇지 않은 경우 user.home으로 전송

할 일 마감 시간에 멘션을 주는 기능

---

src/etc/querySolvedAC.ts

replace '&' to url-encoded char in querySolvedAC

Fix bug in todoHW

---

src/database/alarm.ts
src/database/user.ts
src/module/onDailyGreenGold.ts
src/module/todo/onTodoHW.ts

기존의 alarm 기반 숙제 갱신에서 자연스럽게 migrate 가능

숙제 시점 & 주기 설정가능

---

src/database/alarm.ts

Bugs don't disappear... They keep blazing

---

.github/workflows/pull-test.yml
.github/workflows/pull.yml
src/module/onMessage.ts
src/module/todo/index.ts

사람마다 하나씩 default 비서 "비서실장"을 설정할 수 있습니다.
비서실장에게 하는 명령을 "$"으로 대체할 수 있습니다.
e.g. `cstodo add 다이아올솔브 -> $ a 다이아올솔브`
비서실장을 "$+ cstodo"와 같이 변경할 수 있습니다.

비서실장 기능 추가
